### PR TITLE
Make regular expressions matching URLs more reliable

### LINKED ISSUE #4: If the URL contains Chinese content, the regular expression for extracting links is not reliable.
The following example:

```nvda中文站https://www.nvdacn.com/```

The add-on displays Chinese content in the links list.

### PR DESCRIPTION
**Pull request by cary-rowen**
Hi @ibrahim-s 

close #4 

I modified the regex for matching URLs to be more reliable.
We can test the new version before it is released.

Thanks

### CODE REVIEW

**Comment by cary-rowen** [comment]
Merge this for testing before release.

**Comment by ibrahim-s** [comment]
Hi @cary-rowen 
my dear friend
I really have two points to make
first
what is this protocole nvdaremote
I do not think this is a known protocols in urls
really I am not sure why you included it
second
try to test this
www.google.com
your regular expression will not consider it a link
I think we have to include these form of urls in our extracted links
I am really still testing it 
best
ibrahim

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 

I'm sorry I didn't provide more information.

First:

nvdaremote:// is a link to the nvdaremote add-on, it is a custom protocol but it should be popular among NVDA users.

Like the link below, if you have nvdaremote installed then you can easily open it to control another computer: 

nvdaremote://nr.smzjh.com?key=1234&mode=slave

You can see more information [here](https://github.com/NVDARemote/NVDARemote),
After opening the above nvdaremote repo you just need to press the letter H to find "Sharing your session" for more infromation.

second:
With a simple modification we can match links that do not contain the protocol prefix,.

But what needs to be clear is whether we match the link of nvaccess.org, or we only need to match www.nvaccess.org

Thanks

**Comment by ibrahim-s** [comment]
Hi Cary
with respect to second issue,
of course we need to match www.nvaccess.org and not nvaccess.org
with respect to first point
really in spite I am not a professional user of nvdaremote access addon
but I think this is a very specific protocol for a very specific region
and as far as I have understood it, it may sometimes raise a security issue.
when some one wants to open this type of links, he should know what he 
is doing
otherwise he may find his machine controlled by another machine or computer.
I really prefer, in extracting links to be more generalized, links that 
we are familiar and used by most users
to conclude, I am really not in favor of including nvdaremote protocol 
in our regular expression.
cheers
ibrahim

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 

I can certainly respect your opinion about nvdaremote. But I don't think it poses a security risk, because whether we are controlling another machine or being controlled by another machine, there is always a dialog when we open the link to remind the user of the current action.
This dialog will tell the user what the current action is, and it will only connect when the user clicks the "Yes" button inside the dialog.
Even if the link we open is a common protocol such as https/http, we can't guarantee it is secure, can it?
Also, for www.nvaccess.org or nvaccess.org and https://www.nvaccess.org can we match all three types?
If all types are present, we can put entries starting with https/http/www at the front of the list.
Put the entries that may or may not be URLs after, since browsers obviously can handle non-protocol addresses like nvaccess.org, and maybe it's useful to users as well.

All the best

Cary

**Comment by ibrahim-s** [comment]
Hi Cary
Well you may be right, but just I prefer to be on the safe side
nvdaremote is a special thing, and suppose the user is not used enough to it
he may in the dialog box press the yes button. we can not suppose all 
users are professionals.
so let us stay on the safe side
according of types of urls
you see, I have examined to put in an emaill message
www.nvaccess.org and nvaccess.org
the first is considered by thunderbird a link, but the second did not
so in general I consider the link should be prefexed either by https:// 
or http:// or www.
and all other forms I consider them as not general and I am not 
interested of them.
so I think just changing the regular expression to:
url_re = re.compile(r"(?:https?://|fttp://|www\.)[^ ,.?!#%=+][^ ][^ 
\t\n\r\f\v]*")
this basically will solve the issue that you have raised, and I think 
that is sufficient step.
all the best
ibrahim

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 


I agree with you, please let us put safety first.
So let's revert this PR and test the regex you provided.

All the best

Cary

**Pull request merged**
