### PR TITLE
Updated add-on templates, updated for compatibility with NVDA2023.1

### PR DESCRIPTION
**Pull request by cary-rowen**
## Changes
1. Updated the latest add-on template.
2. Make it compatible with NVDA2023.1.
3. Updated documentation in English and Simplified Chinese.
4.

### CODE REVIEW

**Comment by ibrahim-s** [comment]
Hi @cary-rowen 
Really I do not understand the benefit of the files related to vscode, and the benefit of the file .pre-commit-config.yaml
I want you to tell me in plane text what is the added value of these files, and how they may help us, for really I want to understand no more, and by the way I really use notepad++, and do not know any thing about vscode editor.
I will merge after that, and I have a suggestion for you then.
Thank you always for your activity and hard work
regards

**Comment by cary-rowen** [comment]
Hello,

1. VS Code is more active, driven by the community, and has more plug-ins to choose from. Of course, this is a matter of opinion. You can use the Notepad++ you are used to.
2. I like to make the code more standardized. In the new version of the add-on template, there is flake8 configuration, which can make the code more readable when used with VS Code.
3. A new version of the add-on template can generate the add-on metadata required by NVDA Store, although NVDA Store is under development.
4. As for '.pre-commit-config.yaml', I haven't used it yet.
Hope this explains some of my thoughts on this PR.

Thanks

**Comment by ibrahim-s** [comment]
Hi @cary-rowen 
It seems that I do not have enough information about all those issues until now.
OK then, I really appreciate your work, big thanks.
regards

**Comment by cary-rowen** [comment]
Hi, @ibrahim-s 
You are free to not merge this at all, if you don't have much interest in it 😝
thanks and everything went well

**Comment by ibrahim-s** [comment]
Hi @cary-rowen 
You know that you are a partner in this addon, you can push directly, and you do not need me to merge your work. and you by the way did not pushed the binary to github, for I noticed that the download link is not working now.
I want to say that really until now, I did not use the new addon template, and also I have submitted search with to addon store, but did not know if submition succeeded or not, I do not always follow all messages on addons mailing list, so I miss sometimes lots of things.
I am not sure what you mean by 😝
but you know, In some people's tradition it means greeting, so I will greet you the same way
regards

**Comment by cary-rowen** [comment]
Hi, @ibrahim-s 

Yes I know.
Thank you for your trust in me.
I've now released version 2.8 and now the add-on is downloading normally via the link in the document.
Yes, I greet you with this little emoji.
Hope it doesn't confuse you.
Anyway, all is well my friend.

Best
Cary

**Pull request merged**
