### PR TITLE
Added feature to extract links from last spoken ; added feature to open directly with default browser when there is only one link.

### PR DESCRIPTION
**Pull request by cary-rowen**
Hi @ibrahim-s 

This PR follows up the discussion in #1, I have implemented the following features:

*	Now, You can extract the links from the text in last spoken.
*	You can use the options in the settings panel to decide whether to open it directly with the default browser when there is only one link
*	Remove duplicates after extracting URL
*	The readme has also been updated

But sorry, I didn't split these commits into separate PRs.

Since my native language is not English, you might be able to check the Readme again to make it better.

Thanks

### CODE REVIEW

**Comment by cary-rowen** [comment]
@ibrahim-s 

Hi, I made the changes as you suggested in #2 

Also, regarding the code of lastSpoken, I refer to a part from another of your add-ons. This needs to be clarified.

Best
Cary

**Comment by ibrahim-s** [comment]
Hi @cary-rowen 
Well these are very good added features
I really appreciate this big contribution, and professional work
just when I will make a new release, I want to say
that I will make the check box for open directly if only one link, I will make it unchecked by default. for this is an added feature, and if the user wants it he can checks it in setting panel.
Couple of days, and I will release the new version with these new beautiful features.
Great job
Thank you very much
ibrahim

**Comment by cary-rowen** [comment]
Glad you are happy with this PR

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 

Glad you are happy with this PR,

You are right, the option should be unchecked by default, which is more in line with the gesture description under the input help, So, please revise it.
BTW, do you have plans to add new features before releasing a new version? I would consider submitting a simplified Chinese translation of the add-on, or it would be necessary for us to notify translators in other regions to update their translations as well.

Best

Cary

**Comment by ibrahim-s** [comment]
Hi Cary
Yes do not worry, I will revise it
As for additional features, no I do not think I will add anything else 
for now.
but just some time to review it, and make a development version, and if 
you want at that time you may make a pull request to add simplified 
Chinese translation .
My friend this addon is not an official addon, so we are free to add 
anything at any time.
And by the way, in the coming releases I will mention you as a second 
author of this addon
And if you wish to get access to the repo, I will gladly do that of course.
All the best
ibrahim

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 

OK, I'm willing to make this add-on even better.

Thanks

**Pull request merged**
