### PR TITLE
enhance hyper link menu code, so now it can access and work for more …

### PR DESCRIPTION
**Pull request by ibrahim-s**
Hi @cary-rowen 
This pull request is an enhancement to the old hyper link menu code,
for a lot of times in some pages like facebook for instance, the old code fails to get the destination of the link, and subsequently menu does not open.
Really the code in NVDA core, has been enhanced and changed, and I have made use of that and used the new code to get the destination of the link, and by testing I find it now better, and more links can be accessed and opened with hyper link menu.
Hope to get your review and opinion.

### CODE REVIEW

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 
Nice improvement, looks good to me.

**Comment by ibrahim-s** [comment]
@cary-rowen 
Thank you dear Cary
and I feel this addon is useful and could be on NVDA store
what do you think
regards

**Comment by cary-rowen** [comment]
Yes, I totally agree.

**Comment by ibrahim-s** [comment]
OK, @cary-rowen 
I will try to make a stable version for NVDA 2023.3, and submit it to the store, and see.

Thanks for your activity for NVDA, and being a partner in this addon
kind regards

**Comment by cary-rowen** [comment]
Thanks for your efforts and I look forward to seeing it in NVDA add-on store.

**Pull request merged**
