### PR TITLE
Revert "Make regular expressions matching URLs more reliable"

### PR DESCRIPTION
**Pull request by cary-rowen**
Reverts ibrahim-s/openLinkWith#5

need further testing.

### CODE REVIEW

**Comment by cary-rowen** [comment]
Here are some test examples, let's use the latest commit to test the ability to extract links from selected text.
Just ctrl+A on the PR page and press the gesture to extract the link from the selected text:
https://www.123pan.com/s/A6cA-wWHJh
https://cloud.189.cn/web/share?code=BRz2u2QRBvye
https://pan.baidu.com/s/1V1B5yFNifv_V29QZwZ6aTw

**Comment by ibrahim-s** [comment]
Hi @cary-rowen 
I think this is OK
and basically it addresses the issue of connecting other characters to the beginning of the url
I really have tested it , and I am satisfied with it
Thank you @cary-rowen 
I will merge this, and you are free to ad simplified Chinease translation
and for the mean time I am busy a little bit
so my friend you are free to publish a stable version 2.7 of the addon
All the best
ibrahim

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 

I've released version 2.7 and it looks fine so far.

Best

Cary

**Comment by ibrahim-s** [comment]
Thank you @cary-rowen 
for your good work

**Pull request merged**
