### PR TITLE
Updates in Russian documentation

### PR DESCRIPTION
**Pull request by Kostenkov-2021**
Russian readme.md file has been updated.

### CODE REVIEW

**Comment by ibrahim-s** [comment]
Hi @Kostenkov-2021 
If I want to submit to addon store, I must make a new version
So  what do you prefer
make a new version 3.2.2, without mentioning changes for 3.2.2 in readme.
and in this case the download link will change to 3.2.2 in readme
is this alright for you?

regards

**Comment by Kostenkov-2021** [comment]
Yes, that's alright.Отправлено с iPhone27 марта 2024 г., в 02:15, ibrahim-s ***@***.***> написал(а):﻿
Hi @Kostenkov-2021
If I want to submit to addon store, I must make a new version
So  what do you prefer
make a new version 3.2.2, without mentioning changes for 3.2.2 in readme.
and in this case the download link will change to 3.2.2 in readme
is this alright for you?
regards

**Comment by ibrahim-s** [comment]
Hi @Kostenkov-2021 
OK, I will make the necessary changes right now.

**Comment by ibrahim-s** [comment]
Hi @Kostenkov-2021 
All done, it is now on the store with the changes applied.
greetings

**Pull request merged**
